name: Fetch → Preprocess → Analyze

on: push
permissions:
  contents: write        # allow the bot to commit results.csv

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}   # expose the secret to every step
    steps:
      # 1  Source code
      - uses: actions/checkout@v4                     # latest checkout action

      # 2  Python runtime
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"                      # use one interpreter for every script 

      # 3  Dependencies (one line = one cache miss)
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install requests tqdm tiktoken openai    # all three scripts covered

      # 4  Download & truncate (writes data_preprocessed/short.json)
      - name: Preprocess data
        run: python preprocess_data.py

      # 5  LLM analysis (reads ./data_preprocessed/short.json)
      - name: Analyze with o4-mini
        run: python use_llm.py

      # 6  Commit the CSV (if it changed)
      - name: Commit results.csv
        run: |
          git config --global user.name  'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add results.csv
          git commit -m "Update analysis results" || echo "Nothing to commit"
          git pull --rebase
          git push
          
